services:
  harborman:
    image: ghcr.io/scholar7r/harborman:1.1.0
    container_name: harborman
    restart: unless-stopped
    command: /workspace/harborman -c /workspace/harborman.yaml
    ports:
      - 80:80
    volumes:
      - ./harborman.yaml:/workspace/harborman.yaml:ro
