name: Testing
on:
  - pull_request

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v7
        with:
          go-version: stable

      - name: unit test
        run: |
          go test ./...
          go test -race ./...
