name: Testing
on:
  - pull_request

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version: stable

      - name: unit test
        run: go test -race ./... -coverprofile=coverage.txt

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
